name: Deploy to AWS EC2

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init & Apply
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"

      - name: Get EC2 IP
        id: getip
        working-directory: infra
        run: |
          EC2_IP=$(terraform output -raw public_ip)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Wait for SSH
        run: |
          echo "Waiting for EC2 SSH to be ready..."
          for i in {1..30}; do
            nc -zv $EC2_IP 22 && echo "SH is up" && break
            echo "Still waiting... ($i)"
            sleep 10
          done

      - name: Deploy App to EC2
        env:
          EC2_USER: ubuntu
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" app/ ${EC2_USER}@${EC2_IP}:/home/${EC2_USER}/app
          ssh -i key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_IP} "cd /home/${EC2_USER}/app && sudo docker compose up -d --build"

